# Generated by Django 3.2 on 2023-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
