# Generated by Django 3.2 on 2023-08-22 11:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_auto_20230822_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='userloginmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userloginmodel',
            name='primary_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
