# Generated by Django 3.2 on 2023-08-22 12:16

from django.db import migrations, models
import password_manager.validators.password_validator


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_auto_20230822_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpasswordsmodel',
            name='password',
            field=models.CharField(max_length=100, validators=[password_manager.validators.password_validator.password_validator]),
        ),
        migrations.AlterField(
            model_name='userloginmodel',
            name='password',
            field=models.CharField(max_length=100, validators=[password_manager.validators.password_validator.password_validator]),
        ),
    ]
